name: production
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
jobs:
    lint:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: setup-python
              uses: actions/setup-python@v2
              with:
                python-version: 3.7
            - name: checkout-main
              uses: actions/checkout@v2
            - name: install-package
              run: pip install -e .[development]
            - name: check-format
              run: autopep8 --recursive --exit-code --diff setup.py metastore/ tests/
            - name: check-lint
              run: pylint setup.py metastore/ tests/
    test:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: setup-python
              uses: actions/setup-python@v2
              with:
                python-version: 3.7
            - name: checkout-main
              uses: actions/checkout@v2
            - name: install-package
              run: pip install -e .[development]
            - name: test-package
              run: pytest
            - name: check-coverage
              run: pytest --cov --cov-fail-under 80
    build-publish:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: setup-python
              uses: actions/setup-python@v2
              with:
                python-version: 3.7
            - name: checkout-main
              uses: actions/checkout@v2
            - name: install-package
              run: pip install -e .[development]
            - name: build-package
              run: python setup.py bdist_wheel
            - name: publish-package
              env:
                TWINE_USERNAME: ${{ secrets.REPOSITORY_USERNAME }}
                TWINE_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
              run: twine upload dist/*
