name: release
on:
    workflow_dispatch:
        inputs:
            release-type:
                type: choice
                required: true
                default: patch
                description: 'Release type'
                options:
                  - major
                  - minor
                  - patch
jobs:
    publish:
        runs-on: ubuntu-latest
        environment: production
        steps:
          - name: setup-python
            uses: actions/setup-python@v2
            with:
                python-version: 3.7
                token: ${{ secrets.REPOSITORY_TOKEN }}
          - name: checkout-main
            uses: actions/checkout@v2
          - name: setup-git
            run: |
                git config --local user.name "Metastore Developers"
                git config --local user.email "metastoredevelopers@gmail.com"
          - name: install-package
            run: pip install -e .[development]
          - name: bump-version
            run: |
                if [ $(git tag) ]; then
                    bumpversion ${{ github.event.inputs.release-type }}
                else
                    bumpversion --current-version 0.0.0 major
                fi
          - name: push-tag
            run: git push origin --tags
